---
title: "md"
output: html_document
date: "2022-12-01"
---

```{r, include=FALSE}
library(dplyr)
library(Seurat)
library(patchwork)
```

```{r, results = "hide"}
mouse.data <- Read10X(data.dir = "/Users/xiaoyizheng/Downloads/Bioinformatik/Bioinfo_Einarbeiten/CellChatSelf/mouse/GSE113854_RAW/")
mouse.data

mouse <- CreateSeuratObject(counts = mouse.data, project = "MoSk", min.cells = 3, min.features = 200)
mouse

mouse[["percent.mt"]] <- PercentageFeatureSet(mouse, pattern = "^MT-") 
```
mitochondrial genes -> Zeichen fuer schlechte Qualitaet
```{r}
VlnPlot(mouse, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3) 
```
#All cells have the same value of percent.mt.(maybe bc already filtered?)
```{r}
head(mouse@meta.data, 5) 
```
Show QC metrics for the first 5 cells
```{r}
mouse.data[c("Igf2", "Cck", "Pf4"), 1:30] #a few genes in the first 30 cells #picked "Igf2", "Cck", "Pf4" according to web
```


### visualize feature-feature relationships
```{r}
plot1 <- FeatureScatter(mouse, feature1 = "nCount_RNA", feature2 = "percent.mt") 
```
---
since all have same mt quality...
```{r}
plot2 <- FeatureScatter(mouse, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
```
positively correlated
```{r}
plot1 + plot2
```